import { chromium } from 'file:///C:/Users/dielp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('response', r => { if (r.status() >= 400 && !r.url().endsWith('/levels/level7.json')) errors.push(`${r.status()} ${r.url()}`); });
async function snapshot() {
  return page.evaluate(async () => {
    const map = JSON.parse(document.querySelector('script[type="importmap"]').textContent).imports;
    return (await import(map['./src_scroll/main.js'])).mechanicsSnapshot();
  });
}
await page.goto('http://127.0.0.1:8766/index.html?fixture=hero-mechanics');
await page.waitForTimeout(900);
await page.screenshot({ path: '_dev/hero-qa-spawn.png' });
await page.keyboard.down('ArrowRight');
await page.waitForTimeout(2500);
await page.keyboard.up('ArrowRight');
await page.keyboard.down('ArrowUp');
await page.waitForTimeout(500);
assert.equal((await snapshot()).animation, 'ladder-up');
await page.screenshot({ path: '_dev/hero-qa-ladder-moving.png' });
await page.waitForTimeout(1600);
await page.keyboard.up('ArrowUp');
await page.screenshot({ path: '_dev/hero-qa-ladder-top.png' });
assert.ok(Math.abs((await snapshot()).y - 226) < 1, 'actual game reaches upper platform');
await page.keyboard.down('ArrowDown');
await page.waitForTimeout(2100);
await page.keyboard.up('ArrowDown');
await page.screenshot({ path: '_dev/hero-qa-ladder-bottom.png' });
assert.ok(Math.abs((await snapshot()).y - 418) < 1, 'actual game reaches lower roof');
await page.keyboard.down('ArrowRight');
await page.waitForTimeout(5200);
await page.keyboard.up('ArrowRight');
const beforeGrapple = await snapshot();
await page.keyboard.down('g');
await page.waitForTimeout(650);
assert.equal((await snapshot()).grappling, true, 'actual G input engages anchor');
assert.ok((await snapshot()).y < beforeGrapple.y - 30, 'grapple pulls the player up');
await page.screenshot({ path: '_dev/hero-qa-grapple.png' });
await page.keyboard.up('g');
await page.waitForTimeout(700);
assert.equal((await snapshot()).grappling, false, 'releasing G disengages');
await page.goto('http://127.0.0.1:8766/hero-lab.html?gait=5');
await page.getByRole('button', { name: 'Walk', exact: true }).click();
await page.waitForFunction(() => document.querySelector('#load-status')?.textContent === '7/7 frames loaded');
await page.getByRole('button', { name: 'Run', exact: true }).click();
await page.waitForFunction(() => document.querySelector('#load-status')?.textContent === '7/7 frames loaded');
await page.goto('http://127.0.0.1:8766/editor.html');
await page.locator('#ab-traversal-only').check();
await page.waitForTimeout(400);
const contents = await page.locator('#ab-traversal-only').isChecked();
assert.ok(contents, 'Traversal filter is available');
assert.equal(await page.locator('.ab-cell').count(), 2, 'Traversal shows only ladder and anchor');
assert.equal(errors.length, 0, errors.join('\n'));
console.log('PASS: game fixture, ladder keyboard route, all gait frames, Builder Traversal filter; no browser errors.');
await browser.close();
