// GENERATED by scripts/build_info.mjs — do not hand-edit.
export const BUILD = {
  "branch": "agent/aki-editor",
  "shaShort": "44807ff",
  "shaFull": "44807ff8ba5a33658929e038aac601b6f25adbe1",
  "worktree": "overcharge-aki",
  "dirty": true,
  "generated": "2026-10-01T02:51:45.927Z"
};
