// GENERATED by scripts/build_info.mjs — do not hand-edit.
export const BUILD = {
  "branch": "agent/orcha-gameplay",
  "shaShort": "560911a",
  "shaFull": "560911ac45b3d1c06b06d3ec2b1a2dc60c945c19",
  "worktree": "overcharge",
  "dirty": false,
  "generated": "2026-09-29T03:44:15.984Z"
};
