// GENERATED by scripts/build_info.mjs — do not hand-edit.
export const BUILD = {
  "branch": "agent/aki-editor",
  "shaShort": "72b22ee",
  "shaFull": "72b22eeb33da75c9897a46cd0ace719a5f6de0c6",
  "worktree": "overcharge-aki",
  "dirty": true,
  "generated": "2026-10-03T22:18:09.326Z"
};
