import assert from 'node:assert/strict';
import {Level,Player,flat} from './support/headless.mjs';
import {SkySentry,WheelDrone} from '../src_scroll/city-drones.js';
let n=0;const check=(value,label)=>{assert.ok(value,label);n++;};
const l=flat(),w=new WheelDrone({x:200,y:350,patrolLeft:100,patrolRight:600,speed:55});
for(let i=0;i<180;i++)w.update(1/60,l,null);
check(w.y===414,'wheels settle on floor');check(w.x>200,'patrol moves');
for(let i=0;i<900;i++)w.update(1/60,l,null);
check(w.x>=100&&w.x+w.w<=600,'patrol stays in bounds');
const cliff=flat();for(let row=14;row<18;row++)for(let col=10;col<40;col++)cliff.tiles[row*40+col]=0;
w.x=270;w.vx=55;w.y=414;for(let i=0;i<120;i++)w.update(1/60,cliff,null);
check(w.x+w.w<=320&&w.y===414,'turns before cliff');
const wall=flat();wall.tiles[13*40+10]=16;
w.x=270;w.vx=55;for(let i=0;i<120;i++)w.update(1/60,wall,null);
check(w.x+w.w<=320,'turns at wall');
const opening=flat(); opening.enemies=new Level({cols:40,tiles:opening.tiles,enemies:[{type:'sky-sentry',x:200,y:330,patrolLeft:100,patrolRight:600},{type:'wheel-drone',x:300,y:414,patrolLeft:100,patrolRight:600}]}).enemies;
check(opening.enemies.some(e=>e instanceof SkySentry),'opening flying drone');
check(opening.enemies.some(e=>e instanceof WheelDrone),'opening wheel drone');
const p=new Player(340,418),s=new SkySentry({x:200,y:330,patrolLeft:100,patrolRight:600,speed:40});
l.enemies=[s,w];let shots=0;const original=s._fire.bind(s);s._fire=(...args)=>{shots++;original(...args);};
for(let i=0;i<20;i++)s.update(1/60,l,p);
check(shots===0&&s.alertState==='alert','warning before shooting');
for(let i=0;i<100;i++)s.update(1/60,l,p);
check(shots>0,'flying drone aims and fires');
s._laser=null;s._fire(1,p);const snap=l.snapshot(),savedAngle=snap.enemies[0]._laser.angle;
s._laser.angle+=1;s.hit(l);s.hit(l);w.hit(l);w.hit(l);
check(!s.alive&&!w.alive&&l.pickups.length===4,'both killable and drop charge');
l.restore(snap);check(s.alive&&w.alive&&s.hp===2&&w.hp===2,'checkpoint revives both');
check(s._laser.angle===savedAngle,'checkpoint restores laser');
s._laser.angle+=1;l.restore(snap);check(s._laser.angle===savedAngle,'snapshot is reusable');
let contacts=0;const victim={x:w.x,y:w.y,w:20,h:30,cx:w.cx,stun(){contacts++;},scatter(){}};
w.tryContact(victim,l);w.tryContact(victim,l);check(contacts===1,'contact cooldown');
console.log(`RESULTS: ${n} passed, 0 failed`);
