import assert from 'node:assert/strict';
import { Level, Player, held, step } from './support/headless.mjs';
const tiles = Array.from({length:20*18},(_,i)=>Math.floor(i/20)>=16?16:0);
const def = {cols:20,tiles,gates:[{id:'exit',x:256,y:448,w:32,h:64,required:8,isExit:true}]};
const level = new Level(def), gate=level.gates[0];
const player=new Player(200,482);player.grounded=true;
held(['ArrowRight']);for(let i=0;i<120;i++)step(player,level);held([]);
assert.ok(player.x>gate.x+gate.w, 'walk past uncharged exit');
assert.ok(!level.complete, 'passing uncharged exit cannot win');
assert.ok(!gate.blocks(256,448,20,30), 'portal is non-solid vertically');
gate.open=true;player.x=256;level.update(0,player);
assert.ok(!level.complete, 'open flag without required charge cannot win');
gate.charged=8;player.x=400;level.update(0,player);
assert.ok(!level.complete, 'remote charging does not complete level');
player.x=256;player.y=300;level.update(0,player);
assert.ok(!level.complete, 'same column on another floor cannot win');
player.y=482;level.update(0,player);
assert.ok(level.complete, 'charged exit contact completes level');
const barrier=new Level({...def,gates:[{id:'barrier',x:256,y:448,w:32,h:64,required:2}]}).gates[0];
assert.ok(barrier.blocksHorizontal(250,20,482,30), 'interior barriers remain solid');
assert.ok(!barrier.blocksHorizontal(250,20,300,30), 'interior barriers remain height-aware');
console.log('RESULTS: 9 passed, 0 failed');
