import assert from 'node:assert/strict';
import { Player, Level, held, step, flat } from './support/headless.mjs';
import { GRAPPLE_ANCHOR_SRC, CLIMBABLE_LADDER_SRC } from '../src_scroll/level.js';
let checks = 0;
const check = (condition, label) => { assert.ok(condition, label); checks++; };
const level = flat(), p = new Player(64, 418);
p.grounded = true;
held(['ArrowRight']); step(p, level);
check(p._sprites.state === 'walk', 'runtime uses walk');
check(p._sprites.currentFrame.src.includes('hero-gait-v5'), 'runtime uses matching PixelLab gait');
held(['ArrowRight', 'ShiftLeft']); for (let i = 0; i < 20; i++) step(p, level);
check(p._sprites.state === 'run', 'Shift selects run');
held([]); step(p, level);
p.charge = 10; // give the test player charge to afford the projectile cost (Chief 2026-10-09)
held(['KeyK']); step(p, level);
check(p._sprites.state === 'projectile-cast', 'K selects casting when a bolt fires');
check(p._bolts.length > 0, 'cast animation accompanies a real projectile');

const ladder = { src: CLIMBABLE_LADDER_SRC, x: 192, y: 256, w: 32, h: 192 };
const climbLevel = new Level({ cols: 20, tiles: Array(360).fill(0), decorations: [ladder] });
const climber = new Player(198, 386);
held([]); step(climber, climbLevel);
held(['ArrowUp']); for (let i = 0; i < 10; i++) step(climber, climbLevel);
check(climber._sprites.state === 'ladder-up', 'ladder-up accompanies upward movement');
held([]); step(climber, climbLevel);
const stillY = climber.y, stillFrame = climber._sprites._current._frame;
for (let i = 0; i < 20; i++) step(climber, climbLevel);
check(climber.y === stillY && climber._sprites._current._frame === stillFrame, 'release holds pose on ladder');
held(['ArrowRight', 'ArrowUp']); step(climber, climbLevel);
check(!climber._ladder && climber.vy < 0, 'Up plus direction jumps off ladder');
climbLevel.tiles[11 * 20 + 6] = 16;
climber.x = 198; climber.y = 386; climber.vy = 0;
held([]); step(climber, climbLevel); held(['ArrowUp']);
for (let i = 0; i < 60; i++) step(climber, climbLevel);
check(climber.y >= 384, 'solid ladder ceiling blocks ascent');
check(new Level({ cols: 20, tiles: Array(360).fill(0), decorations: [{...ladder, rotation: 90}] }).ladders.length === 0, 'sideways ladder is decorative');

const ledgeLevel = flat(); ledgeLevel.tiles[13 * ledgeLevel.cols + 12] = 16;
const ledge = new Player(364, 400); ledge.vy = 40;
held([]); step(ledge, ledgeLevel); held(['ArrowUp', 'ArrowRight']); step(ledge, ledgeLevel);
check(!!ledge._ledgeClimb && ledge._sprites.state === 'ledge-climb', 'reachable edge enters actual climb');
held([]); for (let i = 0; i < 55; i++) step(ledge, ledgeLevel);
check(ledge.grounded && Math.abs(ledge.y + ledge.h - 416) < 1 && ledge.x >= 384, 'climb lands on ledge');
ledgeLevel.tiles[12 * ledgeLevel.cols + 12] = 16;
ledgeLevel.tiles[11 * ledgeLevel.cols + 12] = 16;
const blocked = new Player(364, 400); blocked.vy = 40;
held(['ArrowUp', 'ArrowRight']); step(blocked, ledgeLevel);
check(!blocked._ledgeClimb, 'blocked headroom refuses climb');

const grappleLevel = flat(); grappleLevel.grappleAnchors = [{ x: 180, y: 280 }];
const grappler = new Player(64, 418);
held([]); step(grappler, grappleLevel); held(['KeyG']);
for (let i = 0; i < 30; i++) step(grappler, grappleLevel);
check(!!grappler._grapple && grappler.y < 360, 'G attaches and pulls toward an anchor');
check(grappler._sprites.state === 'grapple', 'grapple motion has matching animation');
held([]); step(grappler, grappleLevel); const releaseY = grappler.y;
for (let i = 0; i < 20; i++) step(grappler, grappleLevel);
check(!grappler._grapple && grappler.y > releaseY, 'release lets gravity resume');
grappleLevel.tiles[10 * grappleLevel.cols + 4] = 16;
const obstructed = new Player(64, 418);
held([]); step(obstructed, grappleLevel); held(['KeyG']); step(obstructed, grappleLevel);
check(!obstructed._grapple, 'solid obstruction refuses grapple');
const anchorDef = { src: GRAPPLE_ANCHOR_SRC, x: 64, y: 64, w: 32, h: 32 };
check(new Level({ cols: 20, tiles: Array(360).fill(0), decorations: [anchorDef] }).grappleAnchors[0].x === 80, 'Builder anchor art defines grapple target');
held([]);
console.log(`RESULTS: ${checks} passed, 0 failed`);
