import assert from 'node:assert/strict';
globalThis.Image=class{complete=true;naturalWidth=512;};
const {Animator,PlayerSprites,HERO_STATES}=await import('../src_scroll/hero-sprites.js');
let count=0;const check=(condition)=>{assert.ok(condition);count++;};
const imgs=Array.from({length:8},()=>new Image());
const one=new Animator(imgs,8,false);one.update(2);check(one._frame===7&&one.done);one.update(3);check(one._frame===7);
one.reset();check(one._frame===0&&!one.done);
const loop=new Animator(imgs,8,true);loop.update(1.25);check(loop._frame===2);
const p=new PlayerSprites();
for(const state of Object.keys(HERO_STATES)){p.setState(state);check(p.state===state&&p.currentFrame);p.setState(state,false);check(p.dir==='west');}
const update=(status={},args=[])=>p.update(.02,false,true,false,false,false,false,0,0,false,status,...args);
update({dead:true,attacking:true});check(p.state==='death');
update({stunned:true});check(p.state==='stunned');
p.update(.01,false,true,true,false,false,false);check(p.state==='absorb');
p.update(.01,false,true,false,false,false,true);check(p.state==='discharge');
update({attacking:true});check(p.state==='energy-strike');
update();check(p.state==='energy-strike');
p.update(1,false,true,false,false,false,false);update();check(p.state==='idle');
p.update(.01,true,true,false,false,false,false,75);check(p.state==='walk');
p.update(.01,true,true,false,true,false,false,120);check(p.state==='run');
p.update(.01,true,true,false,false,true,false,80,-300);check(p.state==='jump'&&p._current._frame===1);
p.setState('walk');p._current._frame=5;p._current._t=.03;
p.setState('run');check(p._current._frame===5);
p.setState('walk',false);check(p._current._frame===5&&p.dir==='west');
update({attacking:true,projectile:true});check(p.state==='projectile-cast');
update();check(p.state==='projectile-cast');
p.update(1,false,true,false,false,false,false);check(p._current.done);
update();check(p.state==='idle');
console.log(`RESULTS: ${count} passed, 0 failed`);
