// build_info.mjs — writes editor/buildinfo.js with the CURRENT branch, short
// SHA and worktree, so Chief can tell at a glance which build is open in the
// browser. This exists because two servers on two worktrees were serving two
// different editors and nothing on screen said which was which.
//
// Run: node scripts/build_info.mjs        (re-run after committing)
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join, basename } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..');
const OUT  = join(ROOT, 'editor', 'buildinfo.js');

function git(args, fallback) {
  try { return execSync('git ' + args, { cwd: ROOT, encoding: 'utf8' }).trim(); }
  catch { return fallback; }
}

const branch    = git('rev-parse --abbrev-ref HEAD', 'unknown');
const shaShort  = git('rev-parse --short HEAD', 'unknown');
const shaFull   = git('rev-parse HEAD', 'unknown');
const dirty     = git('status --porcelain', '') !== '';
const worktree  = basename(ROOT);

const body = `// GENERATED by scripts/build_info.mjs — do not hand-edit.
export const BUILD = ${JSON.stringify({
  branch, shaShort, shaFull, worktree, dirty,
  generated: new Date().toISOString(),
}, null, 2)};
`;
writeFileSync(OUT, body);
console.log(`Wrote ${OUT}`);
console.log(`  BRANCH: ${branch}  SHA: ${shaShort}${dirty ? ' (dirty)' : ''}  worktree: ${worktree}`);
