// build_info.mjs — writes editor/buildinfo.js with the CURRENT branch, short
// SHA and worktree, so Chief can tell at a glance which build is open in the
// browser. This exists because two servers on two worktrees were serving two
// different editors and nothing on screen said which was which.
//
// Run: node scripts/build_info.mjs        (re-run after committing)
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join, basename } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..');
const OUT  = join(ROOT, 'editor', 'buildinfo.js');

function git(args, fallback) {
  try { return execSync('git ' + args, { cwd: ROOT, encoding: 'utf8' }).trim(); }
  catch { return fallback; }
}

const branch    = git('rev-parse --abbrev-ref HEAD', 'unknown');
const shaShort  = git('rev-parse --short HEAD', 'unknown');
const shaFull   = git('rev-parse HEAD', 'unknown');

// Dirty = real uncommitted work. Two exclusions:
//   AKI_STATUS.md        Aki-owned; permanent CRLF-only whitespace diff in this
//                        worktree that we never stage. Would pin the label to
//                        "(uncommitted)" forever and make it useless.
//   editor/buildinfo.js  This script's own output. Regenerating it must not be
//                        what makes the tree look dirty (self-reference).
const IGNORE_DIRTY = ['AKI_STATUS.md', 'editor/buildinfo.js'];
const dirty = git('status --porcelain', '')
  .split('\n')
  .map(l => l.trim())
  .filter(Boolean)
  .filter(l => !IGNORE_DIRTY.some(f => l.endsWith(f)))
  .length > 0;

const worktree  = basename(ROOT);

const body = `// GENERATED by scripts/build_info.mjs — do not hand-edit.
export const BUILD = ${JSON.stringify({
  branch, shaShort, shaFull, worktree, dirty,
  generated: new Date().toISOString(),
}, null, 2)};
`;
writeFileSync(OUT, body);
console.log(`Wrote ${OUT}`);
console.log(`  BRANCH: ${branch}  SHA: ${shaShort}${dirty ? ' (dirty)' : ''}  worktree: ${worktree}`);
